ALTER SESSION SET NLS_LENGTH_SEMANTICS=CHAR;
CREATE TABLE TRANSACTIONS_2
(
   AMOUNT                  NUMBER,
   ARN                     VARCHAR2(23),
   AUTHORIZER              VARCHAR2(16),
   PAN                     VARCHAR2(19),
   CARD_ISSUER             VARCHAR2(4),
   CARD_NETWORK            VARCHAR2(4),
   CARD_BRAND              VARCHAR2(2),
   DESTINATION             VARCHAR2(4),
   EXPIRY_DATE             VARCHAR2(4),
   FRAUD                   NUMBER,
   MSG_TYPE                VARCHAR2(4),
   CONDITION_CODE          VARCHAR2(2),
   ENTRY_MODE              VARCHAR2(3),
   RESPONSE_CODE           NUMBER,
   MCC                     VARCHAR2(4),
   REVERSAL_CODE           VARCHAR2(2),
   TERMINAL_CITY           VARCHAR2(100),
   TERMINAL_DISTANCE       NUMBER,
   COUNTRY_CODE            VARCHAR2(2),
   TERMINAL_ID             VARCHAR2(16),
   MERCHANT_ID             VARCHAR2(19),
   TRAN_CATEGORY           VARCHAR2(1),
   TRAN_CODE               VARCHAR2(2),
   CARD_TYPE               VARCHAR2(1),
   TRAN_DATE               DATE,
   PIN_PRESENT             NUMBER,
   PIN_TRIES               NUMBER,
   ABLE_TO_ENTER_PIN       NUMBER,
   PAN_FROM_CHIP           NUMBER,
   SAME_COUNTRY            NUMBER,
   SEPA_COUNTRY            NUMBER,
   SAME_MERCHANT           NUMBER,
   HIGH_RISK_MCC           NUMBER,
   CARD_NOT_PRESENT        NUMBER,
   TRAN_AT_NIGHT           NUMBER,
   PREVIOUS_TRAN_DECLINED  NUMBER,
   TRAN_DECLINED           NUMBER,
   AMOUNT_DIFF             NUMBER,
   NEIGHBOURING_COUNTRY    NUMBER,
   count_10m                 NUMBER,
   count_60m                 NUMBER,
   count_1d                 NUMBER,
   count_7d                 NUMBER,
   count_30d                NUMBER,
   count_60d                NUMBER,
   sum_1d                   NUMBER,
   sum_7d                   NUMBER,
   sum_30d                  NUMBER,
   sum_60d                  NUMBER,
   avg_tran_amount_1d       NUMBER,
   avg_tran_amount_7d       NUMBER,
   avg_tran_amount_30d      NUMBER,
   avg_tran_amount_60d      NUMBER,
   avg_day_amount_1d        NUMBER,
   avg_day_amount_7d        NUMBER,
   avg_day_amount_30d       NUMBER,
   avg_day_amount_60d       NUMBER,
   count_mcc_10m             NUMBER,
   count_mcc_60m             NUMBER,
   count_mcc_1d             NUMBER,
   count_mcc_7d             NUMBER,
   count_mcc_30d            NUMBER,
   count_mcc_60d            NUMBER,
   sum_mcc_1d               NUMBER,
   sum_mcc_7d               NUMBER,
   sum_mcc_30d              NUMBER,
   sum_mcc_60d              NUMBER,
   avg_mcc_tran_amount_1d   NUMBER,
   avg_mcc_tran_amount_7d   NUMBER,
   avg_mcc_tran_amount_30d  NUMBER,
   avg_mcc_tran_amount_60d  NUMBER,
   avg_mcc_day_amount_1d    NUMBER,
   avg_mcc_day_amount_7d    NUMBER,
   avg_mcc_day_amount_30d   NUMBER,
   avg_mcc_day_amount_60d   NUMBER,
   count_merchant_10m        NUMBER,
   count_merchant_60m        NUMBER,
   count_merchant_1d        NUMBER,
   count_merchant_7d        NUMBER,
   count_merchant_30d       NUMBER,
   count_merchant_60d       NUMBER,
   sum_merchant_1d          NUMBER,
   sum_merchant_7d          NUMBER,
   sum_merchant_30d         NUMBER,
   sum_merchant_60d         NUMBER,
   avg_merchant_tran_amount_1d NUMBER,
   avg_merchant_tran_amount_7d NUMBER,
   avg_merchant_tran_amount_30d NUMBER,
   avg_merchant_tran_amount_60d NUMBER,
   avg_merchant_day_amount_1d NUMBER,
   avg_merchant_day_amount_7d NUMBER,
   avg_merchant_day_amount_30d NUMBER,
   avg_merchant_day_amount_60d NUMBER,
   count_country_10m         NUMBER,
   count_country_60m         NUMBER,
   count_country_1d         NUMBER,
   count_country_7d         NUMBER,
   count_country_30d        NUMBER,
   count_country_60d        NUMBER,
   sum_country_1d           NUMBER,
   sum_country_7d           NUMBER,
   sum_country_30d          NUMBER,
   sum_country_60d          NUMBER,
   avg_country_tran_amount_1d NUMBER,
   avg_country_tran_amount_7d NUMBER,
   avg_country_tran_amount_30d NUMBER,
   avg_country_tran_amount_60d NUMBER,
   avg_country_day_amount_1d NUMBER,
   avg_country_day_amount_7d NUMBER,
   avg_country_day_amount_30d NUMBER,
   avg_country_day_amount_60d NUMBER,
   count_cnp_10m         NUMBER,
   count_cnp_60m         NUMBER,
   count_cnp_1d         NUMBER,
   count_cnp_7d         NUMBER,
   count_cnp_30d        NUMBER,
   count_cnp_60d        NUMBER,
   sum_cnp_1d           NUMBER,
   sum_cnp_7d           NUMBER,
   sum_cnp_30d          NUMBER,
   sum_cnp_60d          NUMBER,
   avg_cnp_tran_amount_1d NUMBER,
   avg_cnp_tran_amount_7d NUMBER,
   avg_cnp_tran_amount_30d NUMBER,
   avg_cnp_tran_amount_60d NUMBER,
   avg_cnp_day_amount_1d NUMBER,
   avg_cnp_day_amount_7d NUMBER,
   avg_cnp_day_amount_30d NUMBER,
   avg_cnp_day_amount_60d NUMBER,
   count_nochip_10m         NUMBER,
   count_nochip_60m         NUMBER,
   count_nochip_1d         NUMBER,
   count_nochip_7d         NUMBER,
   count_nochip_30d        NUMBER,
   count_nochip_60d        NUMBER,
   sum_nochip_1d           NUMBER,
   sum_nochip_7d           NUMBER,
   sum_nochip_30d          NUMBER,
   sum_nochip_60d          NUMBER,
   avg_nochip_tran_amount_1d NUMBER,
   avg_nochip_tran_amount_7d NUMBER,
   avg_nochip_tran_amount_30d NUMBER,
   avg_nochip_tran_amount_60d NUMBER,
   avg_nochip_day_amount_1d NUMBER,
   avg_nochip_day_amount_7d NUMBER,
   avg_nochip_day_amount_30d NUMBER,
   avg_nochip_day_amount_60d NUMBER,
   count_declined_10m         NUMBER,
   count_declined_60m         NUMBER,
   count_declined_1d         NUMBER,
   count_declined_7d         NUMBER,
   count_declined_30d        NUMBER,
   count_declined_60d        NUMBER,
   time_since_prev_tran      NUMBER,
   time_since_prev_mcc_tran  NUMBER,
   time_since_prev_merchant_tran NUMBER,
   time_since_prev_country_tran NUMBER,
   first_tran      NUMBER,
   first_mcc_tran  NUMBER,
   first_merchant_tran NUMBER,
   first_country_tran NUMBER,
   first_cnp_tran NUMBER,
   first_nochip_tran NUMBER,
   first_declined_tran NUMBER,
   TRANSACTION_ID          VARCHAR2(11)
)
PARTITION BY RANGE (TRAN_DATE)
INTERVAL(NUMTODSINTERVAL(7, 'DAY'))
( 
   PARTITION transactions_2_p01 VALUES LESS THAN (TO_DATE('20100104', 'YYYYMMDD')),
   PARTITION transactions_2_p02 VALUES LESS THAN (TO_DATE('20100111', 'YYYYMMDD')),
   PARTITION transactions_2_p03 VALUES LESS THAN (TO_DATE('20100118', 'YYYYMMDD')),
   PARTITION transactions_2_p04 VALUES LESS THAN (TO_DATE('20100125', 'YYYYMMDD')),
   PARTITION transactions_2_p05 VALUES LESS THAN (TO_DATE('20100201', 'YYYYMMDD')),
   PARTITION transactions_2_p06 VALUES LESS THAN (TO_DATE('20100208', 'YYYYMMDD')),
   PARTITION transactions_2_p07 VALUES LESS THAN (TO_DATE('20100215', 'YYYYMMDD')),
   PARTITION transactions_2_p08 VALUES LESS THAN (TO_DATE('20100222', 'YYYYMMDD')),
   PARTITION transactions_2_p09 VALUES LESS THAN (TO_DATE('20100301', 'YYYYMMDD')),
   PARTITION transactions_2_p10 VALUES LESS THAN (TO_DATE('20100308', 'YYYYMMDD')),
   PARTITION transactions_2_p11 VALUES LESS THAN (TO_DATE('20100315', 'YYYYMMDD')),
   PARTITION transactions_2_p12 VALUES LESS THAN (TO_DATE('20100322', 'YYYYMMDD')),
   PARTITION transactions_2_p13 VALUES LESS THAN (TO_DATE('20100329', 'YYYYMMDD')),
   PARTITION transactions_2_p14 VALUES LESS THAN (TO_DATE('20100405', 'YYYYMMDD')),
   PARTITION transactions_2_p15 VALUES LESS THAN (TO_DATE('20100412', 'YYYYMMDD')),
   PARTITION transactions_2_p16 VALUES LESS THAN (TO_DATE('20100419', 'YYYYMMDD')),
   PARTITION transactions_2_p17 VALUES LESS THAN (TO_DATE('20100426', 'YYYYMMDD')),
   PARTITION transactions_2_p18 VALUES LESS THAN (TO_DATE('20100503', 'YYYYMMDD')),
   PARTITION transactions_2_p19 VALUES LESS THAN (TO_DATE('20100510', 'YYYYMMDD')),
   PARTITION transactions_2_p20 VALUES LESS THAN (TO_DATE('20100517', 'YYYYMMDD')),
   PARTITION transactions_2_p21 VALUES LESS THAN (TO_DATE('20100524', 'YYYYMMDD')),
   PARTITION transactions_2_p22 VALUES LESS THAN (TO_DATE('20100531', 'YYYYMMDD')),
   PARTITION transactions_2_p23 VALUES LESS THAN (TO_DATE('20100607', 'YYYYMMDD')),
   PARTITION transactions_2_p24 VALUES LESS THAN (TO_DATE('20100614', 'YYYYMMDD')),
   PARTITION transactions_2_p25 VALUES LESS THAN (TO_DATE('20100621', 'YYYYMMDD')),
   PARTITION transactions_2_p26 VALUES LESS THAN (TO_DATE('20100628', 'YYYYMMDD')),
   PARTITION transactions_2_p27 VALUES LESS THAN (TO_DATE('20100705', 'YYYYMMDD'))
);

CREATE INDEX tran2_arn ON transactions_2 (ARN) LOCAL;
CREATE INDEX tran2_authorizer ON transactions_2 (AUTHORIZER) LOCAL;
CREATE INDEX tran2_pan ON transactions_2 (PAN) LOCAL;
CREATE INDEX tran2_fraud ON transactions_2 (FRAUD) LOCAL;
CREATE INDEX tran2_terminal_city ON transactions_2 (TERMINAL_CITY) LOCAL;
CREATE INDEX tran2_country_code ON transactions_2 (COUNTRY_CODE) LOCAL;
CREATE INDEX tran2_terminal_id ON transactions_2 (TERMINAL_ID) LOCAL;
CREATE INDEX tran2_merchant_id ON transactions_2 (MERCHANT_ID) LOCAL;
CREATE INDEX tran2_mcc ON transactions_2 (MCC) LOCAL;
CREATE INDEX tran2_id ON transactions_2 (TRANSACTION_ID) LOCAL;

COMMIT;
EXIT;
