ALTER SESSION SET NLS_LENGTH_SEMANTICS=CHAR;
CREATE TABLE TRANSACTIONS
(
   AMOUNT                  NUMBER,
   AMOUNT_DEV              NUMBER,
   ARN                     VARCHAR2(23),
   AUTHORIZER              VARCHAR2(16),
   PAN                     VARCHAR2(19),
   TRAN_COUNT_1            NUMBER,
   TRAN_COUNT_7            NUMBER,
   TRAN_COUNT_30           NUMBER,
   AVG_AMOUNT_TRAN_1       NUMBER,
   AVG_AMOUNT_TRAN_7       NUMBER,
   AVG_AMOUNT_TRAN_30      NUMBER,
   AVG_AMOUNT_DAY_1        NUMBER,
   AVG_AMOUNT_DAY_7        NUMBER,
   AVG_AMOUNT_DAY_30       NUMBER,
   CARD_ISSUER             VARCHAR2(4),
   CARD_NETWORK            VARCHAR2(4),
   CARD_BRAND              VARCHAR2(2),
   DESTINATION             VARCHAR2(4),
   EXPIRY_DATE             VARCHAR2(4),
   FRAUD                   NUMBER,
   MSG_TYPE                VARCHAR2(4),
   PIN_PRESENT             NUMBER,
   PIN_TRIES               NUMBER,
   CONDITION_CODE          VARCHAR2(2),
   ENTRY_MODE              VARCHAR2(3),
   PAN_FROM_CHIP           NUMBER,
   ABLE_TO_ENTER_PIN       NUMBER,
   RESPONSE_CODE           NUMBER,
   PREVIOUS_TRAN_DECLINED  NUMBER,
   TRAN_DECLINED           NUMBER,
   MCC                     VARCHAR2(4),
   REVERSAL_CODE           VARCHAR2(2),
   TERMINAL_CITY           VARCHAR2(100),
   TERMINAL_DISTANCE       NUMBER,
   COUNTRY_CODE            VARCHAR2(2),
   SAME_COUNTRY            NUMBER,
   SEPA_COUNTRY            NUMBER,
   NEIGHBOURING_COUNTRY    NUMBER,
   TERMINAL_ID             VARCHAR2(16),
   MERCHANT_ID             VARCHAR2(19),
   SAME_MERCHANT           NUMBER,
   TRAN_COUNT_MCC_1        NUMBER,
   TRAN_COUNT_MCC_7        NUMBER,
   TRAN_COUNT_MCC_30       NUMBER,
   AVG_AMOUNT_TRAN_MCC_1   NUMBER,
   AVG_AMOUNT_TRAN_MCC_7   NUMBER,
   AVG_AMOUNT_TRAN_MCC_30  NUMBER,
   AVG_AMOUNT_DAY_MCC_1    NUMBER,
   AVG_AMOUNT_DAY_MCC_7    NUMBER,
   AVG_AMOUNT_DAY_MCC_30   NUMBER,
   TRAN_CATEGORY           VARCHAR2(1),
   CARD_NOT_PRESENT        NUMBER,
   TRAN_CODE               VARCHAR2(2),
   CARD_TYPE               VARCHAR2(1),
   TRAN_DATE               DATE,
   TIME_SINCE_PREV_TRAN    NUMBER,
   TRAN_ON_WEEKEND         NUMBER,
   TRAN_AT_NIGHT           NUMBER,
   TRANSACTION_ID          VARCHAR2(11)
)
PARTITION BY RANGE (TRAN_DATE)
INTERVAL(NUMTODSINTERVAL(7, 'DAY'))
( 
   PARTITION transactions_p01 VALUES LESS THAN (TO_DATE('20100104', 'YYYYMMDD')),
   PARTITION transactions_p02 VALUES LESS THAN (TO_DATE('20100111', 'YYYYMMDD')),
   PARTITION transactions_p03 VALUES LESS THAN (TO_DATE('20100118', 'YYYYMMDD')),
   PARTITION transactions_p04 VALUES LESS THAN (TO_DATE('20100125', 'YYYYMMDD')),
   PARTITION transactions_p05 VALUES LESS THAN (TO_DATE('20100201', 'YYYYMMDD')),
   PARTITION transactions_p06 VALUES LESS THAN (TO_DATE('20100208', 'YYYYMMDD')),
   PARTITION transactions_p07 VALUES LESS THAN (TO_DATE('20100215', 'YYYYMMDD')),
   PARTITION transactions_p08 VALUES LESS THAN (TO_DATE('20100222', 'YYYYMMDD')),
   PARTITION transactions_p09 VALUES LESS THAN (TO_DATE('20100301', 'YYYYMMDD')),
   PARTITION transactions_p10 VALUES LESS THAN (TO_DATE('20100308', 'YYYYMMDD')),
   PARTITION transactions_p11 VALUES LESS THAN (TO_DATE('20100315', 'YYYYMMDD')),
   PARTITION transactions_p12 VALUES LESS THAN (TO_DATE('20100322', 'YYYYMMDD')),
   PARTITION transactions_p13 VALUES LESS THAN (TO_DATE('20100329', 'YYYYMMDD')),
   PARTITION transactions_p14 VALUES LESS THAN (TO_DATE('20100405', 'YYYYMMDD')),
   PARTITION transactions_p15 VALUES LESS THAN (TO_DATE('20100412', 'YYYYMMDD')),
   PARTITION transactions_p16 VALUES LESS THAN (TO_DATE('20100419', 'YYYYMMDD')),
   PARTITION transactions_p17 VALUES LESS THAN (TO_DATE('20100426', 'YYYYMMDD')),
   PARTITION transactions_p18 VALUES LESS THAN (TO_DATE('20100503', 'YYYYMMDD')),
   PARTITION transactions_p19 VALUES LESS THAN (TO_DATE('20100510', 'YYYYMMDD')),
   PARTITION transactions_p20 VALUES LESS THAN (TO_DATE('20100517', 'YYYYMMDD')),
   PARTITION transactions_p21 VALUES LESS THAN (TO_DATE('20100524', 'YYYYMMDD')),
   PARTITION transactions_p22 VALUES LESS THAN (TO_DATE('20100531', 'YYYYMMDD')),
   PARTITION transactions_p23 VALUES LESS THAN (TO_DATE('20100607', 'YYYYMMDD')),
   PARTITION transactions_p24 VALUES LESS THAN (TO_DATE('20100614', 'YYYYMMDD')),
   PARTITION transactions_p25 VALUES LESS THAN (TO_DATE('20100621', 'YYYYMMDD')),
   PARTITION transactions_p26 VALUES LESS THAN (TO_DATE('20100628', 'YYYYMMDD')),
   PARTITION transactions_p27 VALUES LESS THAN (TO_DATE('20100705', 'YYYYMMDD'))
);

CREATE INDEX tran_arn ON transactions (ARN) LOCAL;
CREATE INDEX tran_authorizer ON transactions (AUTHORIZER) LOCAL;
CREATE INDEX tran_pan ON transactions (PAN) LOCAL;
CREATE INDEX tran_fraud ON transactions (FRAUD) LOCAL;
CREATE INDEX tran_terminal_city ON transactions (TERMINAL_CITY) LOCAL;
CREATE INDEX tran_country_code ON transactions (COUNTRY_CODE) LOCAL;
CREATE INDEX tran_terminal_id ON transactions (TERMINAL_ID) LOCAL;
CREATE INDEX tran_merchant_id ON transactions (MERCHANT_ID) LOCAL;
CREATE INDEX tran_mcc ON transactions (MCC) LOCAL;
CREATE INDEX tran_id ON transactions (TRANSACTION_ID) LOCAL;

COMMIT;
EXIT;
